name: Push to PyPI Dev

on:
  push:
    branches:
      - dev
    tags: []

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install wheel twine
          pip install -r requirements.txt
          pip install -r requirements-test.txt

      - name: Set version
        run: |
          sed -i "" "s/version=\"0.0.2\"/version=\"dev\"/g" setup.py


      - name: Run tests
        run: |
          cd tests
          python -m pytest
          cd .. 

      - name: Build a binary wheel and a source tarball
        run: >-
          python setup.py sdist bdist_wheel

      - name: Publish distribution 📦 to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}